"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import * as THREE from "three";
import { assets } from "@/data/productFacts";

type Props={active:boolean; formed:boolean; reducedMotion:boolean};
function BottlePoints({active,formed,reducedMotion}:{active:boolean;formed:boolean;reducedMotion:boolean}){
  const ref=useRef<THREE.Points>(null),activeStart=useRef<number|null>(null); const [targets,setTargets]=useState<Float32Array>();
  const count=useMemo(()=>typeof window!=="undefined"&&window.innerWidth<768?2200:5200,[]);
  const starts=useMemo(()=>{const a=new Float32Array(count*3);for(let i=0;i<count;i++){a[i*3]=(Math.random()-.5)*12;a[i*3+1]=(Math.random()-.5)*10;a[i*3+2]=(Math.random()-.5)*8;}return a},[count]);
  useEffect(()=>{const img=new Image();img.src=assets.front;img.onload=()=>{const c=document.createElement("canvas"),w=220,h=408;c.width=w;c.height=h;const x=c.getContext("2d",{willReadFrequently:true});if(!x)return;x.drawImage(img,0,0,w,h);const d=x.getImageData(0,0,w,h).data;const opaque:number[]=[];for(let p=0;p<w*h;p++)if(d[p*4+3]>42)opaque.push(p);const a=new Float32Array(count*3);for(let i=0;i<count;i++){const p=opaque[Math.floor(Math.random()*opaque.length)],px=p%w,py=Math.floor(p/w);a[i*3]=(px/w-.5)*3.25;a[i*3+1]=(0.5-py/h)*6.05;a[i*3+2]=(Math.random()-.5)*.18;}setTargets(a)}} ,[count]);
  useFrame(({clock})=>{if(!ref.current||!targets)return;if(active&&activeStart.current===null)activeStart.current=clock.elapsedTime;if(!active&&!formed)activeStart.current=null;const base=reducedMotion||formed?1:active?Math.min(1,Math.max(0,(clock.elapsedTime-(activeStart.current??clock.elapsedTime))/4.8)):0;const pos=ref.current.geometry.attributes.position as THREE.BufferAttribute,a=pos.array as Float32Array;for(let i=0;i<count;i++){const k=i*3,dx=targets[k]-starts[k],dy=targets[k+1]-starts[k+1],distance=Math.min(1,Math.hypot(dx,dy)/8),delay=.18*distance+.08*((i*17)%11)/10,p=Math.min(1,Math.max(0,(base-delay)/(1-delay))),ease=1-Math.pow(1-p,4),curve=Math.sin(p*Math.PI)*(1-ease*.45);a[k]=THREE.MathUtils.lerp(starts[k],targets[k],ease)+Math.sin(i*2.17)*.22*curve;a[k+1]=THREE.MathUtils.lerp(starts[k+1],targets[k+1],ease)+Math.cos(i*1.63+clock.elapsedTime*.5)*.16*curve;a[k+2]=THREE.MathUtils.lerp(starts[k+2],targets[k+2],ease)+Math.sin(i*.71)*.3*curve*(1-p)}pos.needsUpdate=true;ref.current.rotation.y=Math.sin(clock.elapsedTime*.22)*.025*(1-base);const material=ref.current.material as THREE.PointsMaterial;material.size=THREE.MathUtils.lerp(.03,.006,base);material.opacity=formed?.06:THREE.MathUtils.lerp(.92,.25,base)});
  if(!targets)return null;return <points ref={ref}><bufferGeometry><bufferAttribute attach="attributes-position" args={[starts.slice(),3]}/></bufferGeometry><pointsMaterial color="#f3ece5" size={.028} transparent opacity={.9} depthWrite={false} blending={THREE.AdditiveBlending}/></points>
}
export function ParticleBottle(p:Props){return <div className={`particle-canvas ${p.formed?"is-formed":""}`} aria-hidden><Canvas dpr={[1,1.45]} camera={{position:[0,0,7.4],fov:44}} gl={{alpha:true,antialias:false,powerPreference:"high-performance"}}><BottlePoints {...p}/></Canvas></div>}
