"use client";
import { useEffect,useMemo,useRef,useState } from "react";
import { Canvas,useFrame } from "@react-three/fiber";
import * as THREE from "three";
import { assets } from "@/data/productFacts";
type Props={active:boolean;formed:boolean;reducedMotion:boolean};
type DropletData={starts:Float32Array;targets:Float32Array;seeds:Float32Array;sizes:Float32Array};
const vertexShader=`uniform float uTime;uniform float uProgress;uniform float uPixelRatio;attribute vec3 aTarget;attribute float aSeed;attribute float aSize;varying float vLife;float easeOut(float t){return 1.0-pow(1.0-t,3.0);}void main(){float vertical=clamp((aTarget.y+3.1)/6.2,0.0,1.0);float delay=mix(.2,.03,vertical)+fract(aSeed*19.73)*.16;float p=clamp((uProgress-delay)/(1.0-delay),0.0,1.0);float e=easeOut(p);vec3 pos=mix(position,aTarget,e);float arc=sin(p*3.14159265)*(1.0-e);float orbit=(aSeed-.5)*6.28318+uTime*(.12+fract(aSeed*7.0)*.16);pos.x+=cos(orbit)*arc*(.35+fract(aSeed*11.0)*.5);pos.y+=sin(orbit*1.17)*arc*.28;pos.z+=sin(orbit*.83)*arc*.65;pos.xy+=vec2(sin(uTime*.31+aSeed*31.0),cos(uTime*.27+aSeed*23.0))*.018*(1.0-p);vec4 mv=modelViewMatrix*vec4(pos,1.0);float perspective=clamp(7.0/-mv.z,.65,1.8);float settle=1.0-smoothstep(.72,1.0,uProgress)*.72;gl_PointSize=aSize*uPixelRatio*perspective*settle;gl_Position=projectionMatrix*mv;vLife=(1.0-smoothstep(.78,1.0,uProgress))*smoothstep(0.0,.12,p);}`;
const fragmentShader=`precision highp float;varying float vLife;void main(){vec2 p=gl_PointCoord*2.0-1.0;float r=length(p);if(r>1.0)discard;float body=smoothstep(1.0,.15,r);float rim=smoothstep(.98,.72,r)-smoothstep(.72,.5,r);float spec=pow(max(0.0,1.0-length(p-vec2(-.32,.38))*1.75),10.0);float lower=pow(max(0.0,1.0-length(p-vec2(.22,-.3))*2.2),5.0)*.22;vec3 water=mix(vec3(.43,.66,.78),vec3(.94,.98,1.0),body*.72+spec);float alpha=(body*.24+rim*.36+spec*.82+lower)*vLife;gl_FragColor=vec4(water,alpha);}`;
function WaterDroplets({active,formed,reducedMotion}:Props){
  const points=useRef<THREE.Points>(null),start=useRef<number|null>(null),[data,setData]=useState<DropletData>();
  const material=useMemo(()=>new THREE.ShaderMaterial({vertexShader,fragmentShader,transparent:true,depthWrite:false,blending:THREE.NormalBlending,uniforms:{uTime:{value:0},uProgress:{value:0},uPixelRatio:{value:1}}}),[]);
  useEffect(()=>{const mobile=window.innerWidth<768,weak=(navigator.hardwareConcurrency||4)<=4,count=mobile?(weak?1150:1750):weak?2600:4600,img=new Image();img.src=assets.front;img.onload=()=>{const canvas=document.createElement("canvas"),w=240,h=446;canvas.width=w;canvas.height=h;const context=canvas.getContext("2d",{willReadFrequently:true});if(!context)return;context.drawImage(img,0,0,w,h);const pixels=context.getImageData(0,0,w,h).data,opaque:number[]=[];for(let i=0;i<w*h;i++)if(pixels[i*4+3]>58)opaque.push(i);const starts=new Float32Array(count*3),targets=new Float32Array(count*3),seeds=new Float32Array(count),sizes=new Float32Array(count);for(let i=0;i<count;i++){const seed=Math.random(),index=opaque[Math.floor(Math.random()*opaque.length)],x=index%w,y=Math.floor(index/w),k=i*3,depth=(Math.random()-.5)*9;starts[k]=(Math.random()-.5)*(11+Math.abs(depth)*.32);starts[k+1]=(Math.random()-.5)*9;starts[k+2]=depth;targets[k]=(x/w-.5)*3.23;targets[k+1]=(.5-y/h)*6.0;targets[k+2]=(Math.random()-.5)*.12;seeds[i]=seed;sizes[i]=(mobile?4.2:5.1)*(seed>.965?2.2:seed>.82?1.35:.72+seed*.5)}setData({starts,targets,seeds,sizes})};return()=>{img.onload=null}},[]);
  useEffect(()=>()=>material.dispose(),[material]);
  useFrame(({clock,gl})=>{if(!points.current||!data)return;if(active&&start.current===null)start.current=clock.elapsedTime;if(!active&&!formed)start.current=null;const progress=reducedMotion||formed?1:active?Math.min(1,(clock.elapsedTime-(start.current??clock.elapsedTime))/5.2):0;material.uniforms.uTime.value=clock.elapsedTime;material.uniforms.uProgress.value=progress;material.uniforms.uPixelRatio.value=Math.min(gl.getPixelRatio(),1.5)});
  if(!data)return null;return <points ref={points} material={material}><bufferGeometry><bufferAttribute attach="attributes-position" args={[data.starts,3]}/><bufferAttribute attach="attributes-aTarget" args={[data.targets,3]}/><bufferAttribute attach="attributes-aSeed" args={[data.seeds,1]}/><bufferAttribute attach="attributes-aSize" args={[data.sizes,1]}/></bufferGeometry></points>;
}
export function ParticleBottle(props:Props){return <div className={`particle-canvas water-formation ${props.formed?"is-formed":""}`} aria-hidden><Canvas frameloop={props.formed?"demand":"always"} dpr={[.8,1.35]} camera={{position:[0,0,7.4],fov:44}} gl={{alpha:true,antialias:false,powerPreference:"high-performance"}}><WaterDroplets {...props}/></Canvas></div>}
